cypress/support/commands/fixture-commands.js

While writing E2E documentation I noticed several mistakes in the comments of our fixture commands. This PR fixes those comments.

Fix comments in fixture commands

---

package-lock.json
package.json

To simplify Cypress usage in custom projects and give the developer more freedom to choose with version to work with, we decided to add Cypress as peerDependency.

Add cypress as peerDependency

---

cypress/plugins/index.js
package-lock.json
package.json

As the plugin is compatible again, we should re-integrate it in next beta-release. :tada:

Re-integrate cypress-log-to-output plugin

---

cypress/support/commands/api-commands.js

The implementation in Shopware 6 will be changed in NEXT-7554. The E2E testsuite have to adapt this new way of saving the Bearer Token.

Change authentication storage from localStorage to Cookie

---

cypress.json
cypress/support/commands/commands.js
cypress/support/commands/fixture-commands.js
cypress/support/commands/system-commands.js

In current state, there can be problems with using `cy.route` with subfolder as these are cut away in this case. This PR provides a wortkaround. Lets test this fix in a beta release though.

Improve subfolder handling in api requests

---

package-lock.json
package.json
routes/cypress.js

This PR replaces the Express.js server with the native Node.js HTTP server which results in less dependencies for the project.
@leichteckig It would be cool if you could test this in a Docker environment to verify the functionality is still the same?

NTR - Replaces the Express.js server with the native HTTP server

---

README.md
cypress/support/commands/commands.js
package-lock.json
package.json

To make feature development including E2E tests a bit smoother, I want to add two helper commands, that skip or only run a test depending on a feature flag.

NEXT-11531 - Add commands `skipOnFeature` and `onlyOnFeature`

---

cypress/support/commands/api-commands.js

Currently, setting a custom env username and password in the ``cypress.json`` is somewhat broken.
The ``authenticate`` command is searching for a ``username`` property just so that it can select a ``user`` property.
Therefor, setting a ``username`` property will always revert to the default right-hand side value ``admin``,
when a ``user`` property is not present.
Likewise, setting a ``user`` property will also always revert to the default right-hand side value ``admin``,
when a ``username`` property is not present.
The same applies to the ``password`` and ``pass`` properties.
To make the current implementation work, one has to define both properties in the ``cypress.json``:
```json
"env": {
"username": "my-user",
"password": "my-password",
"user": "my-user",
"pass": "my-password"
}
``` …

fix user & pass env properties selection

---

cypress/support/commands/commands.js

This fixes a flaky e2e test with the context menu: https://jira.shopware.com/browse/NEXT-13311
The test failed 1 in 400 times. With this fix, it failed 0 in 1800 times. But i will observer further....

NEXT-13311 - Fix context menu

---

README.md
cypress/support/commands/commands.js

This MR adds another Command `typeMultiSelectAndCheckMultiple` which works on `sw-multi-select` input fields. It allows to specify multiple values which will be selected (see example in `README.md`).
This MR does not touch the existing `typeMultiSelectAndCheck` Command to stay compatible and keep a clean and simple interface with the new one.

Add support for multiple values in multi select inputs

---

cypress/support/service/administration/fixture/product.fixture.js

This fixes a problem in the product-fixture-service when there are multiple categories with the same name.
If there are categories with the same name, the current implementation returns the result as an array of categories,
whereas the code on [line 74](https://github.com/shopware/e2e-testsuite-platform/blob/9fc80a09bdd3985568e7d4ea99c407974ad78407/cypress/support/service/administration/fixture/product.fixture.js#L74) expects an object. Thus the category id (`result.id`) can't be set and the api-call is dismissed.
https://github.com/shopware/e2e-testsuite-platform/blob/9fc80a09bdd3985568e7d4ea99c407974ad78407/cypress/support/service/administration/fixture/product.fixture.js#L74
This fix limits the response from the API to 1 and will therefor always respond with an object, keeping existing …

set category API response limit to 1

---

cypress/support/commands/fixture-commands.js
cypress/support/service/administration/fixture/order.fixture.js

Currently, the administration e2e tests use order fixtures using the store-api to add orders for their tests. Therefore, you can only add orders during the API cart process. But for that, the API user has no rights to add line items of types different from 'product' or nested line items.
For that, this PR adds the addition of `createAdminOrder` to provide a different way to create orders with all line item types.

NEXT-14935 - Add admin order fixtures

---

cypress/support/commands/storefront-api-commands.js
cypress/support/index.js
cypress/support/service/administration/fixture.service.js
cypress/support/service/administration/fixture/order.fixture.js
cypress/support/service/saleschannel/fixture.service.js

The import syntax was changed in a recent major update of `uuid`.
**Old syntax:**
```js
const uuid = require('uuid/v4');
```
**New syntax:**
```js
const { v4: uuid } = require('uuid');
```

chore(deps) - Updates import of uuid/v4 module

---

cypress/support/index.js

This was mistakenly deleted but needs to be reintroduced in order to get the pipeline running again

NEXT-12388 - Reintroduce cypress skip tests

---

cypress/support/commands/api-commands.js
cypress/support/commands/fixture-commands.js
cypress/support/commands/system-commands.js
cypress/support/index.js
cypress/support/service/administration/admin-api.service.js
cypress/support/service/administration/fixture.service.js
cypress/support/service/administration/fixture/property.fixture.js
cypress/support/service/administration/fixture/snippet.fixture.js
cypress/support/service/api.service.js
cypress/support/service/saleschannel/fixture.service.js
package.json

Our e2e tests take really long to execute. After analyzing all requests that are triggered by the cypress tests I've noticed that the most time consuming requests (sum of total request time) are `/api/oauth/token` with a total time of around 10-20%. That peaked my interest and I've discovered that for each request another request to get a new authentication token is triggered. This is obviously pretty wasteful.
Ideally, the access token should be reused as long as it's not expired. This is accomplished by storing the authentication information inside the new cookie `_apiAuth`. This cookie has to be persisted for this to take affect.
```js
Cypress.Cookies.defaults({
preserve: ['_apiAuth']
})
```
Otherwise the cookie is cleared after each test. (This change needs to be implemented in …

NEXT-16227 - Cache auth tokens in `AdminApiService`

---

cypress/support/commands/fixture-commands.js

cy.cleanUpPreviousState requires a callback function to be passed.

NTR - Fix setToInitialState command

---

cypress/support/commands/commands.js
package.json

The command `cy.login` does not work after the first login into the administration. 
We need to clear the cookies before logging in again.

NEXT-20166 - Fix cy.login command

---

cypress/support/commands/fixture-commands.js
package.json

The clearCookies command does not clear all cypress cookies and this leads to an broken token in the cookies. This happens only in subdomains aka "http://shopware.subfolder.test"

NEXT-21187 - fix cypress acl tests in subdomains

---

cypress/support/commands/storefront-api-commands.js
package.json

We want to deprecate and then remove the StoreApiProxy from the Storefront proxy as it makes regularly problems and is just a shortcut to creating own custom controllers.
So we remove the proxy usage here and use the store-api directly

NEXT-20396 - Remove StoreApiProxy usage from storefront scope

---

cypress/support/service/fixture/product-wishlist.fixture.js
cypress/support/service/saleschannel/fixture/order.fixture.js
package.json

Currently, some API endpoints return a ContextTokenResponse and some passes the new token using a response header
We should make unify it to the response header, as the response body is mostly encoded entities or other structs

NEXT-17944 - Unify the way to manipulate the context token variable

---

cypress/support/CHANGELOG.md
cypress/support/commands/api-commands.js
package.json

The expiry was not set correctly because the administration mutates it to an absolute time value

Fix expiry value

---

cypress/support/commands/commands.js
package.json

The `createDefaultSalesChannel` command was failing, because it searched for the use by the name: `USA` this has name has recently however changed to be `United States of America`. This PR changes the condition to search for the ISO3 code `USA`, which should stay the same.

Fix create default sales channel command
